all:
	javac model/PeerInfo.java
	javac custom/Util.java
	javac custom/Config.java
	javac model/HandShakeMessage.java
	javac model/Message.java
	javac controller/Log.java
	javac controller/ArgReader.java
	javac controller/BitfieldManager.java
	javac controller/FileManager.java
	javac controller/MessageHandler.java
	javac controller/PeerInfoManager.java
	javac model/Connection.java
	javac controller/MyTimer.java
	javac controller/peerProcess.java
	
clean:
	rm -rf ./bin/controller/*.class ./bin/custom/*.class ./bin/model/*.class  *.log